### PR TITLE
Write an initial script that fetches tasks, abbrs, and taskfile

### LINKED ISSUE #2: Implement `init.sh`
This is what gets called when you want to create a new `taskfile`, and includes:

- prompting the user for the `abbrs`, `tasks`, and `commands`,
- indexing the directory and `taskfile` to the `taskfiles` configuration file,
- appending the missing local `abbrs` to the global `abbrs` configuration file.

### PR DESCRIPTION
**Pull request by davidomarf**
Closes #2

### CODE REVIEW

**Comment by quevangel** [comment]
An issue I found: The naming of the `init` function.  It should be named `tasks-init` or something like that.

**Comment by quevangel** [comment]
We must consider that this thing will be sourced in the user's shell and I think we shouldn't pollute it with non-namespaced-identifiers.

**Comment by quevangel** [comment]
In the same line of thought, I think it would be beneficial to make the auxiliary functions only defined inside the "external"/"user-invocable" init function.

**Comment by quevangel** [comment]
On second thought, maybe this can be dealed with just defining that tasks.sh will contain all avaiable public functions sourcing our files inside the functions.   That is, inside tasks.sh there would be something like this:

`
function tasks-init()
{
  source init.sh;
  init;
}
`

**Comment by quevangel** [comment]
image

**Comment by quevangel** [comment]
image

**Comment by davidomarf** [comment]
k lmao

**Comment by davidomarf** [comment]
I prefer fixing the scope of the functions and replacing `init` with `tasks-init`.

**Pull request closed without merging**
